### ISSUE TITLE
Problem Compiling 'time' example

### ISSUE THREAD

**Issue by ChrisHayward-dev** [hideakitai/DS323x#1]
I have two problems compiling the example 'time' program.  
1. the macro PM is defined in Arduino.h (somewhere).  I can work around it by #undef prior to including the header file
2. There is some sort of assignment error when using DataTime now,
In file included from C:\Users\00011114\AppData\Local\Temp\arduino_modified_sketch_540583\time.ino:2:0:
C:\Users\00011114\Documents\Arduino\libraries\DS323x/DS323x.h: In instantiation of 'int8_t arduino::ds323x::DS323x_<WireType>::readBytes(arduino::ds323x::DS323x_<WireType>::Reg, uint8_t, const uint8_t*, const uint8_t*) [with WireType = TwoWire; int8_t = signed char; uint8_t = unsigned char]':
C:\Users\00011114\Documents\Arduino\libraries\DS323x/DS323x.h:472:22:   required from 'uint8_t arduino::ds323x::DS323x_<WireType>::readByte(arduino::ds323x::DS323x_<WireType>::Reg, uint8_t) [with WireType = TwoWire; uint8_t = unsigned char]'
C:\Users\00011114\Documents\Arduino\libraries\DS323x/DS323x.h:115:54:   required from 'uint8_t arduino::ds323x::DS323x_<WireType>::month() [with WireType = TwoWire; uint8_t = unsigned char]'
C:\Users\00011114\Documents\Arduino\libraries\DS323x/DS323x.h:108:55:   required from 'DateTime arduino::ds323x::DS323x_<WireType>::now() [with WireType = TwoWire]'
C:\Users\00011114\AppData\Local\Temp\arduino_modified_sketch_540583\time.ino:18:28:   required from here
C:\Users\00011114\Documents\Arduino\libraries\DS323x/DS323x.h:510:29: error: assignment of read-only location '*(data + ((sizetype)count))'
                 data[count] = wire->read() & mask[count];

**Comment by hideakitai** [comment]
Thanks, please tell me more information e.g. your board, firmware version, IDE version, etc.

**Comment by ChrisHayward-dev** [comment]
thank-you

Using Arduino 1.8.13 IDE
Board is Adafruit Feather M0

**Comment by hideakitai** [comment]
@ChrisHayward-dev Thanks! I've fixed the bug in v0.1.1. Please check if it works.

**Comment by ChrisHayward-dev** [comment]
Most excellent.  I think there may still be a minor error in the temperature() function.  At least mine shows temperatures of 1408.75. Otherwise most of the functions I've tried have worked well.

**Comment by hideakitai** [comment]
@ChrisHayward-dev Thanks! Maybe the latest master branch works. Can you check it?

**Comment by hideakitai** [comment]
@ChrisHayward-dev Sorry there was cast bug, please check it in the current latest master branch.

**Comment by ChrisHayward-dev** [comment]
Thank-you!

**Comment by hideakitai** [comment]
Thanks for reporting!
